# redislabs/ru101-lab
FROM redislabs/virtual-lab-ide:4.0.10

# PIP dependencies for RU101
RUN set -ex && \
    pip install --upgrade pip && \
	pip install --upgrade --no-cache-dir Faker

# Files required by RU101
ADD redisu/ru101/__init__.py /src/redisu/ru101/__init__.py
ADD redisu/ru101/common /src/redisu/ru101/common

ADD redisu/ru101/data/gen.py /src/redisu/ru101/data/gen.py
ADD redisu/ru101/data/ru101.json /src/redisu/ru101/data/ru101.json
ADD redisu/ru101/data/venues.json /src/redisu/ru101/data/venues.json

ADD redisu/ru101/uc01-faceted-search /src/redisu/ru101/uc01-faceted-search 
ADD redisu/ru101/uc02-inventory-control /src/redisu/ru101/uc02-inventory-control
ADD redisu/ru101/uc03-seat-reservation /src/redisu/ru101/uc03-seat-reservation
ADD redisu/ru101/uc04-notifications /src/redisu/ru101/uc04-notifications
ADD redisu/ru101/uc05-finding-venues /src/redisu/ru101/uc05-finding-venues

ADD redisu/utils /src/redisu/utils
ADD redisu/__init__.py /src/redisu/__init__.py
RUN chown -R student:student /src/redisu

# Base rdb files
ADD redisu/dumps/ru101.rdb /data/dump.rdb
RUN chown redis:redis /data/dump.rdb

ENV PYTHONPATH .:/src
