# redisuniversity/ru102j-lab
FROM redisuniversity/virtual-lab-ide:5.0.3

ENV LD_LIBRARY_PATH /usr/lib/redis/modules/
ENV PATH="/usr/lib/jvm/java-1.8-openjdk/bin:${PATH}"

RUN set -ex && \
        apk add --no-cache \
                coreutils \
                g++ \
      linux-headers \
                make \
      openjdk8 \ 
      maven \
      emacs \
      git && \
      mkdir -p /usr/src/redistimeseries && \
      cd /usr/src/redistimeseries/ && \
      git clone https://github.com/RedisLabsModules/RedisTimeSeries.git && \
      cd RedisTimeSeries && \
      git submodule init && \
      git submodule update && \
      cd src && \
      make all && \
      mkdir -p /usr/lib/redis/modules && \
      cp redistimeseries.so /usr/lib/redis/modules && \
      mkdir /src/redisu/project

RUN set -ex && apk add --no-cache nss

# Supervisord config
ADD supervisord.conf /etc/

ADD project /src/redisu/project

RUN set -ex && \
    cd /src/redisu/project && \
    mvn compile
