# redisuniversity/ru102j-lab
FROM redisuniversity/virtual-lab-ide:5.0.3

ENV LD_LIBRARY_PATH /usr/lib/redis/modules/
ENV PATH="/usr/lib/jvm/java-1.8-openjdk/bin:${PATH}"

RUN set -ex && \
        apk add --no-cache \
                coreutils \
                g++ \
      linux-headers \
                make \
      openjdk8 \ 
      maven \
      emacs \
      ngrep \
      git && \
      mkdir -p /usr/src/redistimeseries && \
      cd /usr/src/redistimeseries/ && \
      git clone https://github.com/RedisLabsModules/RedisTimeSeries.git && \
      cd RedisTimeSeries && \
      git checkout tags/v1.0.0 -b 1.00 && \
      git submodule init && \
      git submodule update && \
      cd src && \
      make all && \
      mkdir -p /usr/lib/redis/modules && \
      cp redistimeseries.so /usr/lib/redis/modules && \
      mkdir /src/redisu/project

RUN set -ex && apk add --no-cache nss

# Add a welcome message
ADD .logo /src/redisu/.logo

# Add the sample project
ADD project /src/redisu/project

# Supervisord tweaks
ADD supervisord.conf /etc/

ADD .logo /home/student/.logo

RUN set -ex && \
    cd /src/redisu/project && \
    mvn compile

RUN chown -R student:student /src/redisu
