# redisuniversity/ru202-lab
FROM redisuniversity/virtual-lab-ide:$REDIS_VERSION

RUN set -ex && \
  	apk add --no-cache \
  		coreutils \
  		g++ \
      linux-headers \
  		make \
  		musl-dev \
      libc6-compat

# RU202 files
ADD .logo /home/student/.logo

RUN chown -R student:student /src/redisu

# Entry page
ADD entry.html /var/lib/nginx/html/
